### ISSUE TITLE
PreferenceScreen annotation leads to StrictMode exception

### ISSUE THREAD

**Issue by kemsky** [excilys/androidannotations#1454]
StrictMode policy violation; ~duration=22 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=63 violation=2

addPreferencesFromResource is called from onCreate (UI Thread).

**Comment by WonderCsabo** [comment]
I never saw this error before. Do you use a PreferenceFragment or
PreferenceActivity? Where this method should be called?

**Comment by kemsky** [comment]
I'm using PreferenceFragment v4 and i got exception with StrictMode enabled:

06-06 07:01:57.617  11842-11842/com.dmsapplication D/StrictMode﹕ StrictMode policy violation; ~duration=22 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=63 violation=2
            at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1137)
            at android.app.SharedPreferencesImpl.awaitLoadedLocked(SharedPreferencesImpl.java:202)
            at android.app.SharedPreferencesImpl.contains(SharedPreferencesImpl.java:267)
            at android.preference.Preference.dispatchSetInitialValue(Preference.java:1371)
            at android.preference.Preference.onAttachedToHierarchy(Preference.java:1171)
            at android.preference.PreferenceGroup.addPreference(PreferenceGroup.java:167)
            at android.preference.PreferenceGroup.addItemFromInflater(PreferenceGroup.java:108)
            at android.preference.PreferenceGroup.addItemFromInflater(PreferenceGroup.java:45)
            at android.preference.GenericInflater.rInflate(GenericInflater.java:488)
            at android.preference.GenericInflater.rInflate(GenericInflater.java:493)
            at android.preference.GenericInflater.inflate(GenericInflater.java:326)
            at android.preference.GenericInflater.inflate(GenericInflater.java:263)
            at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:272)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at android.support.v4.preference.PreferenceManagerCompat.inflateFromResource(PreferenceManagerCompat.java:148)
            at android.support.v4.preference.PreferenceFragment.addPreferencesFromResource(PreferenceFragment.java:226)
            at com.dmsapplication.FragmentPreference_.onCreate(FragmentPreference_.java:32)

**Comment by WonderCsabo** [comment]
I think you should ignore that violation. The JavaDoc says you call that
method in onCreate.
http://developer.android.com/reference/android/preference/PreferenceFragment.html

**Comment by WonderCsabo** [comment]
Please note that strict mode is just flagging any disk reads on the Ui
thread without more logic. Actually we must call this method on the Ui
thread, because It creates views.

**Comment by WonderCsabo** [comment]
I am closing this because this is not an AA issue.
