### ISSUE TITLE
Null Pointer in AnnotationHelper:356

### ISSUE THREAD

**Issue by elliptic1** [excilys/androidannotations#1476]
Error:(58, 21) error: Something went wrong: Unexpected error in AndroidAnnotations 3.2!
You should check if there is already an issue about it on https://github.com/excilys/androidannotations/search?q=java.lang.RuntimeException&type=Issues
If none exists, please open a new one with the following content and tell us if you can reproduce it or not. Don't forget to give us as much information as you can (like parts of your code in failure).
Java version: javac 1.7.0_79
Javac processors options: androidManifestFile=/home/todd/workspace/barnes-noble/app/build/intermediates/manifests/full/debug/AndroidManifest.xml, resourcePackageName=com.ff.acme
Stacktrace: java.lang.RuntimeException: java.lang.NullPointerException
at org.androidannotations.helper.AnnotationHelper.extractAnnotationParameter(AnnotationHelper.java:356)
at org.androidannotations.helper.AnnotationHelper.extractAnnotationResIdValueParameter(AnnotationHelper.java:318)
at org.androidannotations.helper.AnnotationHelper.extractAnnotationResIdValueParameter(AnnotationHelper.java:311)
at org.androidannotations.helper.IdValidatorHelper.resIdsExist(IdValidatorHelper.java:44)
at org.androidannotations.handler.EActivityHandler.validate(EActivityHandler.java:55)
at org.androidannotations.handler.BaseAnnotationHandler.validate(BaseAnnotationHandler.java:108)
at org.androidannotations.process.ModelValidator.validateThrowing(ModelValidator.java:79)
at org.androidannotations.process.ModelValidator.validate(ModelValidator.java:66)
at org.androidannotations.AndroidAnnotationProcessor.validateAnnotations(AndroidAnnotationProcessor.java:234)
at org.androidannotations.AndroidAnnotationProcessor.processThrowing(AndroidAnnotationProcessor.java:183)
at org.androidannotations.AndroidAnnotationProcessor.process(AndroidAnnotationProcessor.java:113)
at 
Caused by: java.lang.NullPointerException
at org.androidannotations.helper.AnnotationHelper.extractAnnotationParameter(AnnotationHelper.java:346)
... 98 more
Thrown from: com.ff.acme.activities
Element (ClassSymbol): package com.ff.acme.activities;
```java
@EActivity
public class AcmeLauncher extends com.ff.acme.helpers.activities.AnalyticsEnabledActivity implements java.lang.Runnable, TimerService_.OnBindListener {

public AcmeLauncher();
private static final int[] RES_IDS;
private static final int[] STRING_IDS;
private static final java.lang.Class<?>[] CLASSES;
public static final java.lang.String START_SESSION_ALERT_ACTION = "com.ff.acme.StartSessionAlert";
public static final java.lang.String START_AD_SLIDER_ACTION = "com.ff.acme.StartAdSlider";
private static final java.lang.String TAG = "ACME";
private static final long TIME_OUT = 30000L;
private CTAButton ctaButton;
private com.ff.acme.services.CTAAdService.CTAServiceConnection connection;
private boolean isIdle;
private boolean buttonClick;
private java.lang.String campaign;
private android.os.Handler handler;
private com.ff.acme.helpers.AppClearerFragment appClearer;
private android.content.BroadcastReceiver mStartSliderReceiver;
private android.content.IntentFilter mIntentFilter;

@java.lang.Override
public void onCreate(android.os.Bundle savedInstanceState);

private void setUpAppClearer();

public void onResume();

public void onPause();

@java.lang.Override
protected void onNewIntent(android.content.Intent intent);

private void initLayout(com.ff.acme.views.LauncherLayout layout);

@java.lang.Override
public boolean onKeyDown(int keyCode,
android.view.KeyEvent event);

public void buttonClick(java.lang.Class<?> activity);

@java.lang.Override
public void onStart();

@java.lang.Override
public boolean onTouchEvent(android.view.MotionEvent e);

@java.lang.Override
public void run();

void touch();

@java.lang.Override
public void onBind(TimerService_.TimerServiceConnection connection);
}
```

**Comment by WonderCsabo** [comment]
Can you check out other `@EActivity` annotations in your code? I think you put something wrong to the parameter.

**Comment by WonderCsabo** [comment]
This is weird we get an NPE at [this point](https://github.com/excilys/androidannotations/blob/427d3f8/AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/helper/AnnotationHelper.java#L346), which means either the annotation or its class is `null`, neither should happen at all. :confused:

**Comment by WonderCsabo** [comment]
No answer since 15 days, i am closing this issue. Please reopen if you have anything to share.
