### ISSUE TITLE
java.lang.NullPointerException ValidatorHelper.java:390

### ISSUE THREAD

**Issue by xiaowogua** [excilys/androidannotations#1596]
You should check if there is already an issue about it on https://github.com/excilys/androidannotations/search?q=java.lang.NullPointerException&type=Issues
If none exists, please open a new one with the following content and tell us if you can reproduce it or not. Don't forget to give us as much information as you can (like parts of your code in failure).
Java version: javac 1.7.0_40
Javac processors options: phase=BUILD
Stacktrace: java.lang.NullPointerException
	at org.androidannotations.helper.ValidatorHelper.elementHasAnnotationSafe(ValidatorHelper.java:390)
	at org.androidannotations.helper.ValidatorHelper.typeHasAnnotation(ValidatorHelper.java:368)
	at org.androidannotations.helper.ValidatorHelper.typeOrTargetValueHasAnnotation(ValidatorHelper.java:378)
	at org.androidannotations.handler.BeanHandler.validate(BeanHandler.java:54)
	at org.androidannotations.handler.BaseAnnotationHandler.validate(BaseAnnotationHandler.java:114)
	at org.androidannotations.process.ModelValidator.validateThrowing(ModelValidator.java:79)
	at org.androidannotations.process.ModelValidator.validate(ModelValidator.java:66)
	at org.androidannotations.AndroidAnnotationProcessor.validateAnnotations(AndroidAnnotationProcessor.java:233)
	at org.androidannotations.AndroidAnnotationProcessor.processThrowing(AndroidAnnotationProcessor.java:182)
	at org.androidannotations.AndroidAnnotationProcessor.process(AndroidAnnotationProcessor.java:112)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:139)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:121)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:159)
	at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:134)
	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:820)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:434)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:365)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.compile(BatchImageBuilder.java:178)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:302)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:60)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:254)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:173)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:726)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:199)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:239)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:292)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:295)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:351)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:374)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)
Thrown from: com.sxit.coopmall.page.fragment.HallFragment
Element (VariableElementImpl): hallService

**Comment by WonderCsabo** [comment]
Can you share com.sxit.coopmall.page.fragment.HallFragment?

**Comment by xiaowogua** [comment]
package com.sxit.coopmall.page.fragment;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.androidannotations.annotations.AfterViews;
import org.androidannotations.annotations.Bean;
import org.androidannotations.annotations.EFragment;
import org.androidannotations.annotations.ViewById;
import org.androidannotations.annotations.res.StringArrayRes;

import android.content.Intent;
import android.view.View;
import android.widget.AdapterView;
import android.widget.AdapterView.OnItemClickListener;
import android.widget.GridView;

import com.sxit.coopmall.R;
import com.sxit.coopmall.adapter.HallBuyFruitItemAdapter;
import com.sxit.coopmall.adapter.HallMenuItemAdapter;
import com.sxit.coopmall.adapter.HallRecommendItemAdapter;
import com.sxit.coopmall.base.component.BaseFragment;
import com.sxit.coopmall.http.RdaResultPack;
import com.sxit.coopmall.mimplement.HallServiceImplement;
import com.sxit.coopmall.mservice.HallService;
import com.sxit.coopmall.page.activity.HallHotCommodityListActivity;
import com.sxit.coopmall.page.activity.HallHotCommodityListActivity_;
import com.sxit.coopmall.page.activity.HallProducingDirectSupplyListActivity_;

@EFragment(R.layout.fragment_hall)
public class HallFragment extends BaseFragment {

	@ViewById
	GridView hall_menu_grid;// 大厅菜单
	@ViewById
	GridView hall_domestic_fruit_grid;// 国产水果
	@ViewById
	GridView hall_imported_fruit_grid;// 进口水果
	@ViewById
	GridView hall_recommend_grid;// 智能推荐
	@ViewById
	GridView hall_like_grid;// 猜你喜欢

	@StringArrayRes(R.array.hall_menu)
	String[] menu_title;
	@StringArrayRes(R.array.hall_domestic)
	String[] domestic_title;
	@StringArrayRes(R.array.hall_imported)
	String[] imported_title;

	int[] menu_icon = { R.drawable.hall_menu_icon1, R.drawable.hall_menu_icon2, R.drawable.hall_menu_icon3, R.drawable.hall_menu_icon4, R.drawable.hall_menu_icon5, R.drawable.hall_menu_icon6 };
	int[] domestic_icon = { R.drawable.hall_fruits_btn1, R.drawable.hall_fruits_btn2, R.drawable.hall_fruits_btn3, R.drawable.hall_fruits_btn4, R.drawable.hall_fruits_btn5, R.drawable.hall_fruits_btn6, R.drawable.hall_fruits_btn7, R.drawable.hall_fruits_btn8 };
	int[] recommend_icon = { R.drawable.hall_fruits_btn9, R.drawable.hall_fruits_btn10, R.drawable.hall_fruits_btn11, R.drawable.hall_fruits_btn12, R.drawable.hall_fruits_btn13, R.drawable.hall_fruits_btn14, R.drawable.hall_fruits_btn15, R.drawable.hall_fruits_btn8 };

	Class[] menu_Activity = { HallHotCommodityListActivity_.class, HallHotCommodityListActivity_.class, HallHotCommodityListActivity_.class, HallHotCommodityListActivity.class, HallProducingDirectSupplyListActivity_.class, HallHotCommodityListActivity.class };

	HallMenuItemAdapter adapterMenu;// 我要买 导航
	HallBuyFruitItemAdapter adapterDomestic;// 国产水果
	HallBuyFruitItemAdapter adapterImported;// 进口水果
	HallRecommendItemAdapter adapterRecommend;

	@Bean(HallServiceImplement.class)
	HallService hallService;

	@AfterViews
	void init() {

		hallService.hallBuy("", 10, 1);

		adapterMenu = new HallMenuItemAdapter(menu_title, menu_icon);
		hall_menu_grid.setAdapter(adapterMenu);

		adapterDomestic = new HallBuyFruitItemAdapter(domestic_title, domestic_icon);
		hall_domestic_fruit_grid.setAdapter(adapterDomestic);

		adapterImported = new HallBuyFruitItemAdapter(imported_title, recommend_icon);
		hall_imported_fruit_grid.setAdapter(adapterImported);

		adapterRecommend = new HallRecommendItemAdapter(GetData());
		hall_recommend_grid.setAdapter(adapterRecommend);

		hall_like_grid.setAdapter(adapterRecommend);

		hall_menu_grid.setOnItemClickListener(new OnItemClickListener() {

			@Override
			public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
				startActivity(new Intent(HallFragment.this.getActivity(), menu_Activity[position]).putExtra("type", position));
			}
		});
	}

	public List<Map<String, String>> GetData() {
		List<Map<String, String>> data = new ArrayList<Map<String, String>>();

		for (int i = 0; i < 4; i++) {
			Map<String, String> map = new HashMap<String, String>();
			map.put("title", "2015新鲜山楂冰糖葫芦专用山东水果批发");
			map.put("special", "13");
			map.put("decimal", ".00元");
			map.put("unit", "/箱");
			map.put("original", "0.66元/斤");
			data.add(map);
		}

		return data;
	}

	@Override
	protected void onEventMainThread(RdaResultPack http) {
		if (http.Match(hallService.This(), "hallBuy")) {

			if (http.Success()) {

			} else if (http.HttpFail()) {
				// Alert("服务器连接失败，请稍后再试！");
			} else if (http.ServerError()) {
				// Alert("暂无数据");
			}

		}
	}
}

**Comment by xiaowogua** [comment]
I fount the reason,thank you

**Comment by WonderCsabo** [comment]
Please share it so others can learn from it, or maybe we could fix the
crash.

**Comment by xiaowogua** [comment]
It was our mistake, we forgot some class so they couldn't be import  (⊙﹏⊙)b

**Comment by WonderCsabo** [comment]
OK, thanks.
