### ISSUE TITLE
Android studio 2.0 beta

### ISSUE THREAD

**Issue by rankorn** [excilys/androidannotations#1691]
I am having some hard time building my project with the new Android studio 2.0 beta.

It seems that the annotated classes are generated, but the gradle plugin cannot find them during compile.

I have upgraded to android-apt 1.8, but it still does not work.

Any idea how to make it build?

**Comment by WonderCsabo** [comment]
@rankorn so i guess the issue was resolved? Maybe you could share the problem and solution for the sake of other users.

**Comment by rankorn** [comment]
Apparently you already introduced a solution right here that I haven't noticed before posting..
https://github.com/excilys/androidannotations/issues/1639

**Comment by OlegDokuka** [comment]
+1 It is not working with new 'com.android.tools.build:gradle:2.0.0-beta2'

**Comment by OlegDokuka** [comment]
java.lang.VerifyError: ua/smartsteamshop/mobile/android/ui/MainActivity_$IntentBuilder_
                                                                                    at ua.smartsteamshop.mobile.android.ui.MainActivity_.intent(MainActivity_.java:74)
                                                                                    at ua.smartsteamshop.mobile.android.ui.LoginActivity.loginResult(LoginActivity.java:155)
                                                                                    at ua.smartsteamshop.mobile.android.ui.LoginActivity_.access$2(LoginActivity_.java:1)
                                                                                    at ua.smartsteamshop.mobile.android.ui.LoginActivity_$3.run(LoginActivity_.java:125)
                                                                                    at android.os.Handler.handleCallback(Handler.java:808)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                                    at android.os.Looper.loop(Looper.java:193)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5551)
                                                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                    at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:730)
                                                                                    at dalvik.system.NativeStart.main(Native Method)

**Comment by WonderCsabo** [comment]
This is out if scope of AndroidAnnotations unfortunately. Instant Run does not really work with annotation processors, yet. We cannot do anything about this.

**Comment by rankorn** [comment]
@WonderCsabo I disagree.. I managed to get Instant Run work perfectly with my app which uses AndroidAnnotations heavily.
Did upgrade Android-apt plugin to 1.8, but I am not sure it was necessary, and using AA 4.0-Snapshot it seems to work great!

**Comment by WonderCsabo** [comment]
@OlegDokuka 's problem has nothing to do with android-apt version. The problem is that Instant Run does not handle the inner class change correctly in the generated class. If you did not encounter this bug before, you are lucky.

**Comment by rankorn** [comment]
So I'm a lucky guy :-)
Hopefully it will not pop up, since Instant Run rocks!

**Comment by OlegDokuka** [comment]
So, Should I use intent builder directly instead of generated one?

**Comment by WonderCsabo** [comment]
You can try to avoid accessing the generated builder, although i am not sure it will help.
But one of the `advantages` of AA that you can use the intent builder...

**Comment by OlegDokuka** [comment]
So, I`m starting my Activity like this

``` java
 MainActivity_.intent(LoginActivity.this).start();
```

Where is the occurrence of the problem?

**Comment by WonderCsabo** [comment]
I do not know the exact problem unfortunately...

**Comment by OlegDokuka** [comment]
Oh... okay, thank you. I will try to work around this problem)
