### ISSUE TITLE
If  Add   compile 'com.tencent.bugly:crashreport:1.2.9' ,   Could not find class 'org.springframework.web.client.RestTemplate' 

### ISSUE THREAD

**Issue by han361769045** [excilys/androidannotations#1695]
# **log:**
02-14 10:58:40.259 2828-2828/com.zczczy.leo.fuwuwangapp E/dalvikvm: Could not find class 'org.springframework.web.client.RestTemplate', referenced from method com.zczczy.leo.fuwuwangapp.rest.NewMyRestClient_.<init>
02-14 10:58:41.149 2828-2828/com.zczczy.leo.fuwuwangapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: com.zczczy.leo.fuwuwangapp, PID: 2828
                                                                          java.lang.NoClassDefFoundError: org.springframework.web.client.RestTemplate
                                                                              at com.zczczy.leo.fuwuwangapp.rest.NewMyRestClient_.<init>(NewMyRestClient_.java:69)
                                                                              at com.zczczy.leo.fuwuwangapp.rest.MyBackgroundTask_.init_(MyBackgroundTask_.java:51)
                                                                              at com.zczczy.leo.fuwuwangapp.rest.MyBackgroundTask_.<init>(MyBackgroundTask_.java:37)
                                                                              at com.zczczy.leo.fuwuwangapp.rest.MyBackgroundTask_.getInstance_(MyBackgroundTask_.java:41)
                                                                              at com.zczczy.leo.fuwuwangapp.activities.NewIndexActivity_.init_(NewIndexActivity_.java:68)
                                                                              at com.zczczy.leo.fuwuwangapp.activities.NewIndexActivity_.onCreate(NewIndexActivity_.java:51)
                                                                              at android.app.Activity.performCreate(Activity.java:5249)
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2165)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2250)
                                                                              at android.app.ActivityThread.access$900(ActivityThread.java:141)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1213)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:136)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5072)
                                                                              at java.lang.reflect.Method.invokeNative(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:515)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
                                                                              at dalvik.system.NativeStart.main(Native Method)
# **app build.gradle**
apply plugin: 'com.android.application'
apply plugin: 'android-apt'
def AAVersion = '3.3.2'

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
    }
}
apt {
    arguments {
        androidManifestFile variant.outputs[0].processResources.manifestFile
        resourcePackageName 'com.zczczy.leo.fuwuwangapp'
    }
}
android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"

    defaultConfig {
        applicationId "com.zczczy.leo.fuwuwangapp"
        minSdkVersion 16
        targetSdkVersion 23
        versionCode 10
        versionName "1.1"
        multiDexEnabled true
        ndk {
            //设置支持的SO库架构
            abiFilters 'armeabi' //, 'x86', 'armeabi-v7a', 'x86_64', 'arm64-v8a'
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    packagingOptions {
        exclude 'META-INF/DEPENDENCIES.txt'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/dependencies.txt'
        exclude 'META-INF/LGPL2.1'
        exclude 'META-INF/maven/com.belerweb/pinyin4j/pom.xml'
        exclude 'META-INF/maven/com.belerweb/pinyin4j/pom.properties'
    }
}
dependencies {
    apt "org.androidannotations:androidannotations:$AAVersion"
    compile "org.androidannotations:androidannotations-api:$AAVersion"
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.j256.ormlite:ormlite-android:4.48'
    compile 'com.j256.ormlite:ormlite-core:4.48'
    compile 'org.springframework.android:spring-android-rest-template:2.0.0.M3'
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:cardview-v7:23.1.1'
    compile 'com.android.support:recyclerview-v7:23.1.1'
//    compile 'com.android.support:design:23.1.1'
    compile 'com.liulishuo.magicprogresswidget:library:1.0.7'
    compile 'com.belerweb:pinyin4j:2.5.0'
    compile 'com.squareup.okhttp:okhttp:2.7.1'
    compile 'com.nineoldandroids:library:2.4.0'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.google.code.gson:gson:2.5'
    compile 'com.squareup:otto:1.3.8'
    compile 'me.himanshusoni.quantityview:quantity-view:1.1.1'
    compile 'com.daimajia.slider:library:1.1.5@aar'
    compile 'com.fasterxml.jackson.core:jackson-databind:2.6.3'
    compile 'com.marshalchen.ultimaterecyclerview:library:0.3.18'
    compile 'com.tencent.bugly:crashreport:1.2.9' 
    compile project(':zxingcapturelibrary')
}

Why?

**Comment by WonderCsabo** [comment]
This is interesting, because you have the spring dependency declared. You can try two things:
* check that the *libs* folder does not have a conflicting local jar
* do a clean build and then run the app

**Comment by han361769045** [comment]
I done  two things , but it don't work .
can you help me.

**Comment by WonderCsabo** [comment]
Can you run the Gradle `dependencies` task? BTW, if you can share the project we can have a look at it.

**Comment by han361769045** [comment]
the project  https://github.com/zczczy/FuWuWangApp-masternew/tree/shangcheng

**Comment by WonderCsabo** [comment]
I cloned your project, and i cannot reproduce the problem. Also, bugly is totally unrelated to the Spring dependency.

**Comment by han361769045** [comment]
![image](https://cloud.githubusercontent.com/assets/8857329/13349748/b7cb85ea-dcb6-11e5-9323-8aaa618a4c00.png)

Could you uncomment the line and rebuild it ?

**Comment by WonderCsabo** [comment]
I already did.

**Comment by han361769045** [comment]
Thank u ! any suggestion?

**Comment by WonderCsabo** [comment]
Well, i did a clean build obviously, you can try that. BTW, i got this exception when started your app:
```
 java.lang.UnsatisfiedLinkError: No implementation found for long com.baidu.platform.comjni.map.commonmemcache.JNICommonMemCache.Create() (tried Java_com_baidu_platform_comjni_map_commonmemcache_JNICommonMemCache_Create and Java_com_baidu_platform_comjni_map_commonmemcache_JNICommonMemCache_Create__)
                                                                                at com.baidu.platform.comjni.map.commonmemcache.JNICommonMemCache.Create(Native Method)
                                                                                at com.baidu.platform.comjni.map.commonmemcache.a.a(Unknown Source)
                                                                                at com.baidu.platform.comapi.e.c.b(Unknown Source)
                                                                                at com.baidu.mapapi.a.c(Unknown Source)
                                                                                at com.baidu.mapapi.SDKInitializer.initialize(Unknown Source)
                                                                                at com.baidu.mapapi.SDKInitializer.initialize(Unknown Source)
                                                                                at com.zczczy.leo.fuwuwangapp.activities.NewIndexActivity.afterInject(NewIndexActivity.java:58)
                                                                                at com.zczczy.leo.fuwuwangapp.activities.NewIndexActivity_.init_(NewIndexActivity_.java:70)
                                                                                at com.zczczy.leo.fuwuwangapp.activities.NewIndexActivity_.onCreate(NewIndexActivity_.java:51)
```

**Comment by han361769045** [comment]
I clean build and invalidate and restart . but this error still occurs；

 i cannot reproduce the problem ::
java.lang.UnsatisfiedLinkError: No implementation found for long com.baidu.platform.comjni.map.commonmemcache.JNICommonMemCache.Create() (tried Java_com_baidu_platform_comjni_map_commonmemcache_JNICommonMemCache_Create and Java_com_baidu_platform_comjni_map_commonmemcache_JNICommonMemCache_Create__)
                                                                                at com.baidu.platform.comjni.map.commonmemcache.JNICommonMemCache.Create(Native Method)
                                                                                at com.baidu.platform.comjni.map.commonmemcache.a.a(Unknown Source)
                                                                                at com.baidu.platform.comapi.e.c.b(Unknown Source)
                                                                                at com.baidu.mapapi.a.c(Unknown Source)
                                                                                at com.baidu.mapapi.SDKInitializer.initialize(Unknown Source)
                                                                                at com.baidu.mapapi.SDKInitializer.initialize(Unknown Source)
                                                                                at com.zczczy.leo.fuwuwangapp.activities.NewIndexActivity.afterInject(NewIndexActivity.java:58)
                                                                                at com.zczczy.leo.fuwuwangapp.activities.NewIndexActivity_.init_(NewIndexActivity_.java:70)
                                                                                at com.zczczy.leo.fuwuwangapp.activities.NewIndexActivity_.onCreate(NewIndexActivity_.java:51)
