### ISSUE TITLE
Issue with version 4.0.0 - stuck on EApplicationHandler

### ISSUE THREAD

**Issue by githubdoramon** [excilys/androidannotations#1733]
I'm getting this error when trying to build the project:

applicationClassName=com.fleeber.FleeberApplication_, libraryProject=false, debugabble=false, minSdkVersion=15, maxSdkVersion=-1, targetSdkVersion=23]
14:40:33.468 [Daemon worker] INFO  o.a.i.r.ProjectRClassFinder:51 - Found project R class: com.fleeber.R
14:40:33.525 [Daemon worker] INFO  o.a.i.r.AndroidRClassFinder:45 - Found Android class: android.R
14:40:33.559 [Daemon worker] INFO  o.a.i.p.ModelValidator:46 - Validating elements
14:40:33.560 [Daemon worker] DEBUG o.a.i.p.ModelValidator:66 - Validating with EApplicationHandler: [searchRest, notificationRest, pushNotificationsRest, com.fleeber.FleeberApplication, profilesRest, profileRest, profileOpenRest, messagesRest, profileOpenRest, openRest, instrumentsRest, profilesRest, profilesRest, profilesUpdateRest, profilesRest, profileOpenRest, profilesUpdateRest, instrumentsRest, openRest, profileOpenRest, profilesRest, profileRest, notificationPreferencesRest, profilesRest, loginRest, loginRest, openRest, profilesUpdateRest, instrumentsRest]
14:40:33.919 [Daemon worker] ERROR o.a.i.AndroidAnnotationProcessor:249 - Something went wrong: Unexpected error in AndroidAnnotations 4.0.0!
You should check if there is already an issue about it on https://github.com/excilys/androidannotations/search?q=java.lang.ClassCastException&type=Issues
If none exists, please open a new one with the following content and tell us if you can reproduce it or not. Don't forget to give us as much information as you can (like parts of your code in failure).
Java version: javac 1.7.0_71
Javac processors options: androidManifestFile=/Users/fleeber/workspace/fleeber-android/fleeber/build/intermediates/manifests/full/debug/AndroidManifest.xml, resourcePackageName=com.fleeber, logLevel=TRACE
Stacktrace: java.lang.ClassCastException: com.sun.tools.javac.code.Symbol$VarSymbol cannot be cast to javax.lang.model.element.TypeElement
	at org.androidannotations.handler.BaseGeneratingAnnotationHandler.isInnerClass(BaseGeneratingAnnotationHandler.java:52)
	at org.androidannotations.handler.BaseGeneratingAnnotationHandler.validate(BaseGeneratingAnnotationHandler.java:39)
	at org.androidannotations.internal.core.handler.EApplicationHandler.validate(EApplicationHandler.java:39)
	at org.androidannotations.handler.BaseAnnotationHandler.validate(BaseAnnotationHandler.java:65)
	at org.androidannotations.internal.process.ModelValidator.validate(ModelValidator.java:70)
	at org.androidannotations.internal.AndroidAnnotationProcessor.validateAnnotations(AndroidAnnotationProcessor.java:216)
	at org.androidannotations.internal.AndroidAnnotationProcessor.processThrowing(AndroidAnnotationProcessor.java:174)
	at org.androidannotations.internal.AndroidAnnotationProcessor.process(AndroidAnnotationProcessor.java:126)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:793)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:722)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1700(JavacProcessingEnvironment.java:97)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1029)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1163)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1108)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:824)
	at com.sun.tools.javac.main.Main.compile(Main.java:439)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:132)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:45)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:33)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:101)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:50)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:36)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:34)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
	at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:157)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:139)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:93)
	at com.android.build.gradle.tasks.factory.AndroidJavaCompile.compile(AndroidJavaCompile.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:244)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:231)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
	at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:78)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:48)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:66)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

14:40:33.920 [Daemon worker] INFO  o.a.i.p.TimeStats:81 - Time measurements: [Whole Processing = 1137 ms], [Extract Manifest = 536 ms], [Extract Annotations = 147 ms], [Find R Classes = 90 ms], 
14:40:33.920 [Daemon worker] INFO  o.a.i.AndroidAnnotationProcessor:137 - Finish processing
 
No idea how to find what is going wrong

**Comment by linwoain** [comment]
maxSdkVersion = -1 ?? 
how it happened?

**Comment by WonderCsabo** [comment]
From the stack trace it seems you put `@EApplication` annotation to a field. That annotation belongs to a class. For fields, you should use `@App`.

**Comment by WonderCsabo** [comment]
@linwoain that happens when the `maxSdkVersion` is not set, the default value is - 1.

**Comment by githubdoramon** [comment]
@WonderCsabo the only place I use EApplication is on the Application class

@EApplication
public class FleeberApplication extends Application 

And yes... I am not setting maxSdkVersion

**Comment by githubdoramon** [comment]
Here is my full build.gradle

`allprojects {
    repositories {
        maven {
            url 'https://zendesk.artifactoryonline.com/zendesk/repo'
        }
    }
}

buildscript {
    repositories {
        jcenter()
        mavenCentral()
        maven {
            url 'https://maven.fabric.io/public'
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.0-alpha3'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
        classpath 'io.fabric.tools:gradle:1.+'
    }
}

apply plugin: 'com.android.application'
dependencies {
    compile('com.crashlytics.sdk.android:crashlytics:2.5.5@aar') {
        transitive = true;
    }
}

apply plugin: 'com.android.application'
apply plugin: 'android-apt'
apply plugin: 'io.fabric'

apt {
    arguments {
        androidManifestFile variant.outputs[0].processResources.manifestFile
        resourcePackageName 'com.fleeber'
        logLevel 'TRACE'
    }
}

repositories {
    maven { url 'http://dl.bintray.com/populov/maven' }
    mavenCentral()
    mavenLocal()
    maven { url 'https://maven.fabric.io/public' }
    maven { url "https://jitpack.io" }
    jcenter()
}

ext.androidAnnotationsVersion = '4.0.0';
ext.jacksonVersion = '2.2.2';
ext.googleLibrariesVersion = "23.2.1";
ext.googlePlayVersion = "8.4.0";

android {
    defaultConfig.applicationId="com.fleeber"
    useLibrary 'org.apache.http.legacy'
    compileSdkVersion Integer.parseInt(project.ANDROID_BUILD_SDK_VERSION)
    buildToolsVersion project.ANDROID_BUILD_TOOLS_VERSION

    dependencies {
        //Android stuff
        compile "com.android.support:appcompat-v7:${googleLibrariesVersion}"
        compile "com.android.support:cardview-v7:${googleLibrariesVersion}"
        compile "com.android.support:recyclerview-v7:${googleLibrariesVersion}"
        compile "com.android.support:support-v4:${googleLibrariesVersion}"
        compile "com.google.android.gms:play-services-maps:${googlePlayVersion}"
        compile "com.google.android.gms:play-services-auth:${googlePlayVersion}"
        compile "com.google.android.gms:play-services-location:${googlePlayVersion}"
        compile "com.google.android.gms:play-services-analytics:${googlePlayVersion}"
        compile "com.google.android.gms:play-services-gcm:${googlePlayVersion}"
        compile "com.google.android.gms:play-services-appindexing:${googlePlayVersion}"
        compile "com.google.android.gms:play-services:${googlePlayVersion}"

        //Core libraries
        compile 'com.facebook.android:facebook-android-sdk:4.7.0'

        // Fabric.io
        compile('com.crashlytics.sdk.android:crashlytics:2.5.5@aar') {
            transitive = true
        }

        //Zendesk
        compile group: 'com.zendesk', name:'sdk', version:'1.5.1.2'

        //UI libraries
        compile "com.android.support:design:${googleLibrariesVersion}"
        compile "com.splitwise:tokenautocomplete:2.0.3@aar"
        compile "com.viewpagerindicator:library:2.4.1@aar"
        compile "com.sothree.slidinguppanel:library:3.2.1"

        //Images
        compile 'com.facebook.fresco:fresco:0.9.0+'
        compile 'com.facebook.fresco:webpsupport:0.9.0'
        compile 'com.soundcloud.android:android-crop:1.0.0@aar'
        compile 'it.sephiroth.android.library.imagezoom:imagezoom:+'

        //Other
        compile fileTree(dir: 'libs', include: '*.jar')
        compile 'com.google.code.gson:gson:2.4'
        compile 'org.springframework.android:spring-android-rest-template:1.0.1.RELEASE'
        compile "com.fasterxml.jackson.core:jackson-databind:${jacksonVersion}"
        compile "com.fasterxml.jackson.core:jackson-annotations:${jacksonVersion}"
        compile "com.fasterxml.jackson.core:jackson-core:${jacksonVersion}"

        // Android annotations
        apt "org.androidannotations:androidannotations:${androidAnnotationsVersion}"
        compile "org.androidannotations:androidannotations-api:${androidAnnotationsVersion}"
        compile "org.androidannotations:rest-spring:${androidAnnotationsVersion}"
        apt "org.androidannotations:rest-spring:${androidAnnotationsVersion}"


        compile 'com.android.support:multidex:1.0.1' //if multidex is needed
    }

    dexOptions {
        javaMaxHeapSize "4g"
    }

    defaultConfig {
        versionCode 53
        versionName "2.2.6"
        minSdkVersion Integer.parseInt(project.ANDROID_BUILD_MIN_SDK_VERSION)
        targetSdkVersion Integer.parseInt(project.ANDROID_BUILD_TARGET_SDK_VERSION)
        multiDexEnabled = true //if multidex is needed
        renderscriptTargetApi 20
        renderscriptSupportModeEnabled true
    }

    signingConfigs {
        release {
            def signFileProperties = file(System.getenv("HOME") + "/.signing/" + project.name + ".properties")
            if (signFileProperties.exists()) {
                Properties props = new Properties()
                props.load(new FileInputStream(signFileProperties));
                storeFile file(props['keystore.file']);
                storePassword props['keystore.password'];
                keyAlias props['key.alias']
                keyPassword props['key.password'];
            }
        }
    }

    buildTypes {
        debug {
            minifyEnabled false
            debuggable true
            applicationIdSuffix ".debug"
        }
        release {
            signingConfig signingConfigs.release
            debuggable false
            minifyEnabled true
            proguardFiles 'proguard.cfg', 'proguard-fresco.pro', 'proguard-zendesk.pro'
            zipAlignEnabled true
        }
    }

    lintOptions {
        abortOnError false
    }

    packagingOptions {
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
    }

    apply plugin: 'com.google.gms.google-services'
}


def googleServicesJson = 'google-services.json'

task switchToDebug(type: Copy) {
    def buildType = 'debug'
    description = 'Switches to DEBUG google-services.json'
    outputs.upToDateWhen {false}
    from "src/${buildType}"
    include "$googleServicesJson"
    into "."
}

task switchToRelease(type: Copy) {
    def buildType = 'release'
    description = 'Switches to RELEASE google-services.json'
    outputs.upToDateWhen {false}
    from "src/${buildType}/"
    include "$googleServicesJson"
    into "."
}

afterEvaluate {
    processDebugGoogleServices.dependsOn switchToDebug
    processReleaseGoogleServices.dependsOn switchToRelease
}`

**Comment by WonderCsabo** [comment]
Are you sure EApplication os not somewhere on a variable or field? Try search for it first.

**Comment by githubdoramon** [comment]
I searched and found nothing...  Will try to search again

**Comment by WonderCsabo** [comment]
Can you share the class, or better, the project?

**Comment by githubdoramon** [comment]
@WonderCsabo I gave you access to the bitbucket repository

**Comment by WonderCsabo** [comment]
@githubdoramon can you contact me by email?

**Comment by githubdoramon** [comment]
@WonderCsabo just emailed you!!!!

**Comment by alexwambre** [comment]
Hello,

What was the problem?

**Comment by githubdoramon** [comment]
Declaration of the rest plugin... I missed the - api on the name
