### ISSUE TITLE
@Receiver in EFragment - IllegalStateException

### ISSUE THREAD

**Issue by peter9teufel** [excilys/androidannotations#1752]
Hi guys!
I have a problem, I am using @EFragments and have a Receiver method to detect connectivity changes to trigger an automatic reload if the device is connected

`@Receiver(actions = ConnectivityManager.CONNECTIVITY_ACTION)
protected void connectivityChanged(Context context){
             ........
}`

To test things out now connectivity is changed, this is done by switching over to wifi settings and connect either to a wifi which does not provide access to the internet or the stable wifi. Now while being in the wifi settings the app crashes as soon as the connectivityChanged method is called and tries to refresh. It throws an
`java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState`

Stacktrace is as follows:

`Caused by: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
                                                                            at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1489)
                                                                            at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1507)
                                                                            at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:634)
                                                                            at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:613)
                                                                            at com.example.MyFragment.connectivityChanged(MyFragment.java:313)`

I have several fragments in the app that use that mechanism to trigger a refresh so it would be great to get this issue resolved.

Thanks in advance!

**Comment by WonderCsabo** [comment]
This is not an AA issue. You can check the Fragment state inside the method.

**Comment by peter9teufel** [comment]
One more question what you exactly mean by checking the Fragment state.
While the settings app was opened and my app in the background the connectivity changed triggers as explained above, at this point (while in background) I checked whether the FragmentManager has been destroyed (isDestroyed()) which is false, and if the Fragment is attached and visible which are both true. What else could be checked here in the Receiver Callback?

**Comment by WonderCsabo** [comment]
This is the responsibility of your code, sorry. AA just calls the method, it does know anything about what lays inside - and it should not know that. As you can see the exception happens in your code, not in the generated class:
```java
com.example.MyFragment.connectivityChanged(MyFragment.java:313)
```

**Comment by peter9teufel** [comment]
Found the issue just a minute ago, sorry for bothering you and thanks for your quick response!

**Comment by WonderCsabo** [comment]
No problem!
