### ISSUE TITLE
Setup issue

### ISSUE THREAD

**Issue by laindow** [excilys/androidannotations#1757]
Hello guys,

    I am trying to setup 4.0.0 release and I got a problems with it.
    I crash on my first activity. I replace my actual package name by xx.xxx.xxxxxxx.myapp.

/*********************************************************************************************************/
04-22 17:09:35.251 15095-15095/xx.xxx.xxxxxxx.myapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: xx.xxx.xxxxxxx.myapp, PID: 15095
                                                                    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{xx.xxx.xxxxxxx.myapp/xx.xxx.xxxxxxx.myapp.views.SplashActivity_}: java.lang.ClassNotFoundException: Didn't find class "xx.xxx.xxxxxxx.myapp.views.SplashActivity_" on path: DexPathList[[zip file "/data/app/xx.xxx.xxxxxxx.myapp-1/base.apk"],nativeLibraryDirectories=[/data/app/xx.xxx.xxxxxxx.myapp-1/lib/arm64, /vendor/lib64, /system/lib64]]
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2970)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3224)
                                                                        at android.app.ActivityThread.access$1000(ActivityThread.java:198)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1682)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:145)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6843)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:372)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
                                                                     Caused by: java.lang.ClassNotFoundException: Didn't find class "xx.xxx.xxxxxxx.myapp.views.SplashActivity_" on path: DexPathList[[zip file "/data/app/xx.xxx.xxxxxxx.myapp-1/base.apk"],nativeLibraryDirectories=[/data/app/xx.xxx.xxxxxxx.myapp-1/lib/arm64, /vendor/lib64, /system/lib64]]
                                                                        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                        at android.app.Instrumentation.newActivity(Instrumentation.java:1080)
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2960)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3224) 
                                                                        at android.app.ActivityThread.access$1000(ActivityThread.java:198) 
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1682) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                        at android.os.Looper.loop(Looper.java:145) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6843) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199) 
                                                                    	Suppressed: java.lang.ClassNotFoundException: Didn't find class "xx.xxx.xxxxxxx.myapp.views.SplashActivity_" on path: DexPathList[[dex file "/data/data/xx.xxx.xxxxxxx.myapp/files/instant-run/dex/slice-support-annotations-23.3.0_44d406a5590b7c96d730d760b482109ca859428b-classes.dex", dex file "/data/data/xx.xxx.xxxxxxx.myapp/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/xx.xxx.xxxxxxx.myapp/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/xx.xxx.xxxxxxx.myapp/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/xx.xxx.xxxxxxx.myapp/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/xx.xxx.xxxxxxx.myapp/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/xx.xxx.xxxxxxx.myapp/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/xx.xxx.xxxxxxx.myapp/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/xx.xxx.xxxxxxx.myapp/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/xx.xxx.xxxxxxx.myapp/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/xx.xxx.xxxxxxx.myapp/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/xx.xxx.xxxxxxx.myapp/files/instant-run/dex/slice-retrofit-2.0.2_ab3e372093bfbb32b3067691af34d2845c7695ce-classes.dex", dex file "/data/data/xx.xxx.xxxxxxx.myapp/files/instant-run/dex/slice-realm-annotations-0.88.2_0d4943e5d0c6c4641d141638d00cddaeee8ec85e-classes.dex", dex file "/data/data/xx.xxx.xxxxxxx.myapp/files/instant-run/dex/slice-okio-1.6.0_2b87c2e9b983e6d67f2792610b46408f000a06d8-classes.dex", dex file "/data/data/xx.xxx.xxxxxxx.myapp/files/instant-run/dex/slice-okhttp-3.2.0_ed9860f35fccf00bca834b446cd85ebf8873369f-classes.dex", dex file "/data/data/xx.xxx.xxxxxxx.myapp/files/instant-run/dex/slice-io.realm-realm-android-library-0.88.2_979d66f733fb6f57de00cd5ddc8d530654d5ce33-classes.dex", dex file "/data/data/xx.xxx.xxxxxxx.myapp/files/instant-run/dex/slice-internal_impl-23.3.0_9c4f29ee05b845fde4132fa817c713465500c1e7-classes.dex", dex file "/data/data/xx.xxx.xxxxxxx.myapp/files/instant-run/dex/slice-gson-2.4_668adf984a7daf3150ba420ba6e2118e63fbbe17-classes.dex", dex file "/data/data/xx.xxx.xxxxxxx.myapp/files/instant-run/dex/slice-even

/*********************************************************************************************************/

**Comment by WonderCsabo** [comment]
The problem is the generated class is not packaged into the APK. Can you post your build scripts?

**Comment by laindow** [comment]
Hello,
 Here build scripts


// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.0.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files

        //Realm integration
        classpath "io.realm:realm-gradle-plugin:0.88.2"
        // replace with the current version of the android-apt plugin
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
    }
}

allprojects {
    repositories {
        jcenter()
        maven {
            url = 'https://oss.sonatype.org/content/repositories/snapshots'
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by laindow** [comment]
`
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.0.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files

        //Realm integration
        classpath "io.realm:realm-gradle-plugin:0.88.2"
        // replace with the current version of the android-apt plugin
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
    }
}

allprojects {
    repositories {
        jcenter()
        maven {
            url = 'https://oss.sonatype.org/content/repositories/snapshots'
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`

**Comment by laindow** [comment]
```

// Top-level build file where you can add configuration options common to all sub-projects/modules.

build script {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:grade:2.0.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files

        //Realm integration
        classpath "io.realm:realm-gradle-plugin:0.88.2"
        // replace with the current version of the android-apt plugin
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
    }
}

all projects {
    repositories {
        jcenter()
        maven {
            url = 'https://oss.sonatype.org/content/repositories/snapshots'
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```

**Comment by laindow** [comment]
```
apply plugin: 'com.android.application'
//Realm integration
apply plugin: 'realm-android'

apply plugin: 'android-apt'
def AAVersion = '4.0.0'

apt {
    arguments {
        androidManifestFile variant.outputs[0]?.processResources?.manifestFile
        // if you have multiple outputs (when using splits), you may want to have other index than 0

        // you should set your package name here if you are using different application IDs
        // resourcePackageName "your.package.name"

        // You can set optional annotation processing options here, like these commented options:
        // logLevel 'INFO'
        // logFile '/var/log/aa.log'
    }
}

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.3"

    defaultConfig {
        applicationId "xx.xxx.xxxxxx.myapp"
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 1
        versionName "1.0.0"
    }

    productFlavors {
        devBuild {
            buildConfigField "String", "SERVER_URL", "\"https://presentlytravelling.files.wordpress.com\""
            versionName "1.0.0"
        }
        betaBuild {
            buildConfigField "String", "SERVER_URL", "\"http://test.app\""
            versionName "1.0.0"
        }
        releaseBuild {
            buildConfigField "String", "SERVER_URL", "\"http://test.app\""
            versionName "1.0.0"
        }
    }

    signingConfigs {
        release {
            storeFile file("/keystore/xxxxxx.jks")
            storePassword "xxxxxx"
            keyAlias "xxxxxx"
            keyPassword "xxxxxx"
        }
        debug {
            storeFile file("/keystore/xxxxxx.jks")
            storePassword "xxxxxx"
            keyAlias "xxxxxx"
            keyPassword "xxxxxx"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:unit:4.12'
    compile 'com.android.support:appcompat-v7:23.3.0'

    //Notifications system
    compile 'org.greenrobot:events:3.0.0'
    //JSON parser
    compile 'com.google.code.gson:son:2.4'
    //Network communication
//    compile 'com.android.volley:volley:1.0.0'
    compile 'com.squareup.retrofit2:retrofit:2.0.2'

    //Android Annotation
    apt "org.androidannotations:androidannotations:$AAVersion"
    compile "org.androidannotations:androidannotations-api:$AAVersion"
}

```

**Comment by WonderCsabo** [comment]
Try disabling instant run and build that way. Please reopen if the issue is not resolved.
