### ISSUE TITLE
NavigationView causes exception on KITKAT

### ISSUE THREAD

**Issue by rohitshampur** [excilys/androidannotations#1819]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     java.lang.RuntimeException: Unable to start activity ComponentInfo{com.uttarainfo.uttara/com.uttarainfo.uttara.activities.MainActivity_}: android.view.InflateException: Binary XML file line #17: Error inflating class android.support.design.widget.NavigationView
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2356)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420)
                                                                         at android.app.ActivityThread.access$600(ActivityThread.java:162)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                         at android.os.Looper.loop(Looper.java:194)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5426)
                                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:525)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:842)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
                                                                         at dalvik.system.NativeStart.main(Native Method)
                                                                      Caused by: android.view.InflateException: Binary XML file line #17: Error inflating class android.support.design.widget.NavigationView
                                                                         at android.view.LayoutInflater.createView(LayoutInflater.java:613)
                                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
                                                                         at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280)
                                                                         at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                         at com.uttarainfo.uttara.activities.MainActivity_.setContentView(MainActivity_.java:55)
                                                                         at com.uttarainfo.uttara.activities.MainActivity_.onCreate(MainActivity_.java:43)
                                                                         at android.app.Activity.performCreate(Activity.java:5194)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1081)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2320)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420) 
                                                                         at android.app.ActivityThread.access$600(ActivityThread.java:162) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                                         at android.os.Looper.loop(Looper.java:194) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5426) 
                                                                         at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:525) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:842) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609) 
                                                                         at dalvik.system.NativeStart.main(Native Method) 
                                                                      Caused by: java.lang.reflect.InvocationTargetException
                                                                         at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                         at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
                                                                         at android.view.LayoutInflater.createView(LayoutInflater.java:587)
                                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687) 
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
                                                                         at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280) 
                                                                         at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                         at com.uttarainfo.uttara.activities.MainActivity_.setContentView(MainActivity_.java:55) 
                                                                         at com.uttarainfo.uttara.activities.MainActivity_.onCreate(MainActivity_.java:43) 
                                                                         at android.app.Activity.performCreate(Activity.java:5194) 
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1081) 
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2320) 
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420) 
                                                                         at android.app.ActivityThread.access$600(ActivityThread.java:162) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                                         at android.os.Looper.loop(Looper.java:194) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5426) 
                                                                         at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:525) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:842) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609) 
                                                                         at dalvik.system.NativeStart.main(Native Method) 
                                                                      Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f020088
                                                                         at android.content.res.Resources.getValue(Resources.java:1337)
                                                                         at android.support.v7.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:313)
                                                                         at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:188)
                                                                         at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:181)
                                                                         at android.support.v7.view.menu.MenuItemImpl.getIcon(MenuItemImpl.java:422)
                                                                         at android.support.design.internal.NavigationMenuPresenter$NavigationMenuAdapter.prepareMenuItems(NavigationMenuPresenter.java:505)
                                                                         at android.support.design.internal.NavigationMenuPresenter$NavigationMenuAdapter.update(NavigationMenuPresenter.java:436)
                                                                         at android.support.design.internal.NavigationMenuPresenter.updateMenuView(NavigationMenuPresenter.java:112)
                                                                         at android.support.design.widget.NavigationView.inflateMenu(NavigationView.java:246)
                                                                         at android.support.design.widget.NavigationView.<init>(NavigationView.java:170)
                                                                         at android.support.design.widget.NavigationView.<init>(NavigationView.java:96)
                                                                         at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                         at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
                                                                         at android.view.LayoutInflater.createView(LayoutInflater.java:587) 
                                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687) 
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
                                                                         at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280) 
                                                                         at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                         at com.uttarainfo.uttara.activities.MainActivity_.setContentView(MainActivity_.java:55) 
                                                                         at com.uttarainfo.uttara.activities.MainActivity_.onCreate(MainActivity_.java:43) 
                                                                         at android.app.Activity.performCreate(Activity.java:5194) 
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1081) 
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2320) 
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420) 
                                                                         at android.app.ActivityThread.access$600(ActivityThread.java:162) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                                         at android.os.Looper.loop(Looper.java:194) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5426) 
                                                                         at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:525) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:842) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609) 
                                                                         at dalvik.system.NativeStart.main(Native Method)

**Comment by dodgex** [comment]
I'm pretty sure this issue has nothing to do with Android Annotations.

- android.view.InflateException: Binary XML file line #17: Error inflating class 
- Caused by: android.view.InflateException: Binary XML file line #17: Error inflating class android.support.design.widget.NavigationView
- Caused by: java.lang.reflect.InvocationTargetException
- Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f020088

according to the stacktrace of the last exception it tries to load a drawable that it can't find. maybe your drawable is in a directory that is not valid for kitkat or the specific device due to its [qualifiers](https://developer.android.com/guide/topics/resources/providing-resources.html)?
